version: "3"
services:
  mongo-rs0-1:
    image: "mongo-start"
    build: ./mongo-rs0-1
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-rs0-1/data:/data/db
    depends_on:
      - "mongo-rs0-2"
      - "mongo-rs0-3"

  mongo-rs0-2:
    image: "mongo"
    command: --replSet rs0
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-rs0-2/data:/data/db

  mongo-rs0-3:
    image: "mongo"
    command: --replSet rs0
    ports:
      - "27019:27017"
    volumes:
      - ./mongo-rs0-3/data:/data/db

  setup-rs:
    image: "mongo"
    working_dir: /app
    volumes:
      - ./setup/setup.sh:/app/setup.sh
      - ./setup/replicaSet.js:/app/replicaSet.js
    depends_on:
      - "mongo-rs0-1"
      - "mongo-rs0-2"
      - "mongo-rs0-3"
    command: "/bin/bash /app/setup.sh"

  web-app:
    container_name: web_app
    restart: always
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - "setup-rs"